### ISSUE TITLE
Wolf not moving

### ISSUE THREAD

**Issue by orkeny** [sebastianstarke/AI4Animation#13]
Hi! I tried to check your Demo project but after I followed your instructions and stored the network parameters the wolf character is not moving if a press the control buttons. I am new to Unity, maybe it is a trivial one. Do you have any suggestions? (Windows 10, Unity 2018.2.0f2)

**Comment by siamaksalman** [comment]
I also tried the Original Human Demo from [this commit](https://github.com/sebastianstarke/AI4Animation/commit/53d6175c10c5090ef46e1c31386847db20ed7cb5) and found a problem at [this line](https://github.com/sebastianstarke/AI4Animation/blob/d17ee1c82fcb4b03fc4c72952d7a880e178282f9/AI4Animation/Assets/Scripts/DeepLearning/Tensor.cs#L31).

**Comment by orkeny** [comment]
After the last commit the same here. But before that the motion didn't work for me like in the released and builded Demo.

**Comment by sebastianstarke** [comment]
Oh yes, I updated the Eigen library plugin and did not recompile it for Windows with the changed API, only for Linux. My bad - it just can't find the function with the proper name. If you pull the project now, it should be working again. Otherwise I'll have to find a Windows computer in order to recompile it with Visual Studio. Please let me know!

**Comment by sebastianstarke** [comment]
Oh yes, I updated the Eigen library plugin and did not recompile it for Windows with the changed API, only for Linux. My bad - it just can't find the function with the proper name. If you pull the project now, it should be working again. Otherwise I'll have to find a Windows computer in order to recompile the plugin with Visual Studio. Please let me know! Thanks.

**Comment by orkeny** [comment]
It works on Windows, thanks a lot!
