### ISSUE TITLE
Index gating in problem

### ISSUE THREAD

**Issue by zhichaoshu** [sebastianstarke/AI4Animation#16]
In AI4Animation/TensorFlow/SIGGRAPH_2018/main.py code:

index_gatingIn = [285, 286, 287, 
                  345, 346, 347, 
                  393, 394, 395, 
                  341, 342, 343,
                  84,  85,  86, 87, 88, 89, 90]

In the paper, it says that the gating input is a subset of x that are the foo end effector velocities, so should the index in line 4 be "441, 442, 443" instead of "341, 342, 343"?

**Comment by sebastianstarke** [comment]
oh yeah, that might be a typo there (3 instead of 4). need to check again though. we reimplemented the code for the MANN to make it more easy for others to try and modify. the gating indices should basically align with the ones shown in the MANN inspector in Unity, so if it's 441, 442, 443" there, it definitely needs to be like that ;) cheers!

**Comment by zhichaoshu** [comment]
Thanks for your response. I double checked the bvh file, if the joint velocities used are LeftHand, RightHand,  LeftFoot and RightFoot, then it should be a typo~
