### ISSUE TITLE
Training and Testing split is missing

### ISSUE THREAD

**Issue by xcyan** [sebastianstarke/AI4Animation#29]
Request to re-open the issue #15

**Comment by YuZhang10** [comment]
I get the same problem, but I find a csharp-based implement in [AI4Animation/SIGGRAPH_2018/Unity/Assets/Scripts/DeepLearning/Models/MANN.cs](https://github.com/sebastianstarke/AI4Animation/blob/master/AI4Animation/SIGGRAPH_2018/Unity/Assets/Scripts/DeepLearning/Models/MANN.cs)
Hope it will help somebody.

**Comment by sebastianstarke** [comment]
The training happens in AI4Animation/Deep Learning outside the Unity project folder, whereas the inference code is a native Eigen-plugin C# implementation in Unity inside the Unity/Assets/Scripts/DeepLearning/Models folder. Or are you referring to the split of training and test data?

**Comment by sebastianstarke** [comment]
The training happens in AI4Animation/Deep Learning outside the Unity project folder, whereas the inference code is a native Eigen-plugin C# implementation in Unity inside the Assets/Scripts/DeepLearning/Models folder. Or were you referring to the split of training and test data?

**Comment by sebastianstarke** [comment]
The training happens in AI4Animation/Deep Learning outside the Unity project folder, whereas the inference code is a native Eigen-plugin C# implementation in Unity inside the Assets/Scripts/DeepLearning/Models folder. Or were you referring to a split of training and test data?

**Comment by YuZhang10** [comment]
For me, I was looking for the inference code, not the test data.

I'm trying to export the MANN's output motion into pybullet, so that a legged robot can imitate it, like this [google-research/motion_imitation](https://github.com/google-research/motion_imitation)
![image](https://user-images.githubusercontent.com/30391848/82023823-72607500-96c1-11ea-8c65-32c500998d16.png)

I wonder whether you could release python-based inference code, if you have implemented any.

Thank you.

**Comment by floodsung** [comment]
@sebastianstarke Could you release a split train set and valid set for experiments? I think it would be very helpful to test different network architectures.
