### ISSUE TITLE
Ballroom dancing dog?

### ISSUE THREAD

**Issue by Qix-** [sebastianstarke/AI4Animation#30]
![image](https://user-images.githubusercontent.com/885648/72323818-e22a0900-36a9-11ea-8b65-8af1f7b1f119.png)
![image](https://user-images.githubusercontent.com/885648/72323841-f1a95200-36a9-11ea-8efb-8655977bcde5.png)

Not sure what's going on here, but I've managed to... well, mangle the dog. Or make him dance, not entirely sure.

1. Make the dog fully sit (hold V for a few seconds)
2. Release V
3. Wait 2 seconds
4. Tap V
5. Repeat steps 3 and 4 repeatedly.

Is this an issue with the network, or just the Unity/demo code?

**Comment by Qix-** [comment]
Welp, I made the mistake of doing this, then hitting W, which made him bolt off screen into the void, only to re-spawn in a super-dog position.

![image](https://user-images.githubusercontent.com/885648/72324238-be1af780-36aa-11ea-9faf-3f7f04cda76b.png)

**Comment by Qix-** [comment]
Found another one:

1. Hold R, F and V all at the same time, for maybe 5 seconds or so.
2. Let go of F.

Screen goes white, dog's velocity is NaNm/s and the confidences for the weights skyrocket. The weight visualizer disappears as well.

**Comment by sebastianstarke** [comment]
That's some cool dances! :D I could assume if multiple one-hots are active simultaneously and the user is trying to sprint at the same time, the system may extrapolate too much because it has never seen such data (like sprinting while sitting/lying/standing).  Probably the code control logic wasn't too much polished here... :) Thanks for pointing those out!

**Comment by sebastianstarke** [comment]
That's some cool dances! I could assume if multiple one-hots are active simultaneously and the user is trying to sprint at the same time, the system may extrapolate too much because it has never seen such data (like sprinting while sitting/lying/standing). Probably the code control logic wasn't too much polished here... :) Thanks for pointing those out!
