### ISSUE TITLE
Wrong Data Processing Results for MANN

### ISSUE THREAD

**Issue by Fiona730** [sebastianstarke/AI4Animation#35]
Hi, I tried to convert the raw motion capture data in MANN into the format for neural nerwork input, using the data processing scripts you provided in Unity (BVHImporter, MotionExporter etc.). However, the resulted Input.txt and Output.txt does not align with the ones you provided, both in trajectory and bone parameter fields. Training MANN with my own txts also displayed weird results, proving that the generated files are wrong.

I looked through the code and everything seems to be right. I haven't alter any of the code you released, and only clicked "Export" botton and added Trajectory Module for each clip in the Motion Editor panel (leaving alone the Style Module because the annotation of styles does not affect other parameters).

Do you have any idea where things might go wrong?

Thank you! :)

**Comment by ANABUR920** [comment]
It also happens to me. Seem like that the Trajectory model does not work very well?

**Comment by sebastianstarke** [comment]
Sorry for the delayed response. It seems I introduced a small bug in the MotionExporter.cs, where the root motion update during export did not match the code during runtime. Fixed this one now.

Regarding the bone parameter fields, can you verify whether the Actor in the motion capture scene has the expected number of bones active? If I remember right, we did not use all joints from the original BVH mocap, so importing and exporting without adjusting the bones you wish to use will likely yield different files. In that case, you'll need to adjust the gating indices since the dimensions for feet velocities will be different.

Regarding the trajectory parameter fields, can you explain which dimensions seem different, or where mismatches appear? Looking at the code, it should be working fine I believe? Happy to help!

**Comment by sebastianstarke** [comment]
Sorry for the delayed response. It seems I introduced a small bug in the MotionExporter.cs when refactoring the code, where the root motion update during export did not match the code during runtime. Fixed this one now.

Regarding the bone parameter fields, can you verify whether the Actor in the motion capture scene has the expected number of bones active? If I remember right, we did not use all joints from the original BVH mocap, so importing and exporting without adjusting the bones you wish to use will likely yield different files. In that case, you'll need to adjust the gating indices since the dimensions for feet velocities will be different. The motion editor is a modular framework, and selecting the bones to be used needs to be done manually once for an actor model. Regarding the trajectory parameter fields, can you explain which dimensions seem different, or where mismatches appear? Looking at the code, it should be working fine I believe?

Let me know, happy to help if needed!

**Comment by sebastianstarke** [comment]
Sorry for the delayed response. It seems I introduced a small bug in the MotionExporter.cs when refactoring the code, where the root motion update during export did not match the code during runtime. Fixed this one now.

Regarding the bone parameter fields, can you verify whether the Actor in the motion capture scene has the expected number of bones active? If I remember right, we did not use all joints from the original BVH mocap, so importing and exporting without adjusting the bones you wish to use will likely yield different files. In that case, you'll need to adjust the gating indices since the dimensions for feet velocities will be different. The motion editor is a modular framework, and selecting the bones to be used needs to be done manually once for an actor model. Regarding the trajectory parameter fields, can you explain which dimensions seem different, or where mismatches appear? Looking at the code, it should be working fine?

Let me know, happy to help if needed!

**Comment by floodsung** [comment]
@sebastianstarke Could you open-source the mocap data style annotation of MANN like what Siggraph 2019 Asia did? Thank you. I found it pretty difficult to export the same dataset as yours.

Also, I have no idea why the rotation of the wolf's neck is wrong when i play the mocap animation in MotionEditor:
<img width="793" alt="Screen Shot 2021-06-21 at 6 18 42 PM" src="https://user-images.githubusercontent.com/3880963/122747101-3da7ef80-d2bd-11eb-9a53-bc09e350348b.png">

**Comment by sebastianstarke** [comment]
Hi @floodsung, yes you are right, this head issue is because the original mocap data is in a non-mirrorable format, but the wolf was skinned under the edited mirrorable rig. Basically, you need to apply a delta rotation to (if I remember right) the neck and tail of 45 degree, which can be done in the motion editor settings tab. And yes, I also planned to recreate the annotation data and make it available soon - unfortunately this was not easily doable at the time when this project was initially started in 2018, but can be done now. Thanks! :)

**Comment by floodsung** [comment]
@sebastianstarke Thanks a lot!
