### ISSUE TITLE
About joint velocity, positions and angles (Mode-adaptive neural network)

### ISSUE THREAD

**Issue by EricGuo5513** [sebastianstarke/AI4Animation#47]
Hi, thanks for your really awesome works. I have one simple question regarding to the implementation. In the paper, the input and output of model both contains joint positions, velocity and orientations (or angles).

However, if I'm not wrong, the joint positions and orientations are interchangable, which means they could be transformed to each other with some formulas. The same happens to velocities and positions. If so, why should we generate them both? I'm also not sure if the positions, velocity and oritentations are generated in parallel, or the velocities and orientations are extracted from the generated positions.

Thanks you in advance. Look forward to your reply.

**Comment by 05120502** [comment]
Hello, I'm a student in China and I want to download this project, but I always get an error in the 2019 NSM unity folder. And I wonder if you have the files. If so, could you please send them to my mailbox? 13689044423@qq.com. I'd appreciate it very gratefully! ! !

**Comment by sebastianstarke** [comment]
It is true that those features for position/rotation/velocity in both global or local space can be somewhat derived from each other, so yeah in theory the network should be able to do learn this. It is also possible to put another function on the input or output to derive them before or after prediction. However, in practice it turns out that including those features in the input separately helps the network a lot and makes learning the movements easier, even if some features act purely autoregressive and are not controlled by the user. In addition, if we learn features in local space, there can be error accumulation after prediction, and including velocity helps the model to keep better temporal coherence for the movements. But right, in general some more compact representation would be desirable. Hope that helps!

**Comment by sebastianstarke** [comment]
It is true that those features for position/rotation/velocity in both global or local space can be somewhat derived from each other, so yeah in theory the network should be able to learn this. It is also possible, as you said, to put another function around the input or output to derive them before or after prediction. However, in practice it turns out that including those features separately helps the network a lot and makes learning the movements easier, even if some features act purely autoregressive and are not controlled by the user. Also, if we learn features in local space there can be error accumulation after prediction, and including velocity helps the model to keep better temporal coherence for the movements. But right, in general some more compact representation would be desirable. Hope that helps!

**Comment by Direct-Leo** [comment]
> Hello, I'm a student in China and I want to download this project, but I always get an error in the 2019 NSM unity folder. And I wonder if you have the files. If so, could you please send them to my mailbox? [13689044423@qq.com](mailto:13689044423@qq.com). I'd appreciate it very gratefully! ! !

I can help you and I'm uploading now, it seems to take a while.

**Comment by miaoYuanyuan** [comment]
@sebastianstarke as we know , with the bone length fixed, the joint position changes along with the joint rotation, so When the prediction joint position and rotations has conflict, what can we do ? for example: after prediction the joint position need Lerp with velocity .but the rotation not change. so the Act.Bone.Transformation.position and rotaion inner has conflict?  

Another question. in the papre 4.2. the joint velocity is modify by the Lerp between a and b , 
b=b1-b2 = (inverse joint position)-(auto-regression joint position). 
but in the Unity Project,
`velocities[i] = Vector3.Lerp(velocities[i], GetFramerate() * (PosePrediction[i] - Actor.Bones[i].Transform.position), 1f/GetFramerate());` 
b is `(PosePrediction[i] - Actor.Bones[i].Transform.position` identity (inverse joint position)-(pivot joint position). the b2 is not identity with the b2 in paper.
