### ISSUE TITLE
IK module

### ISSUE THREAD

**Issue by zll961020** [sebastianstarke/AI4Animation#72]
Hello Sebastian Starke,  I have some question about the IK module in UltimateIK.cs , how does it works? And is there any theoretical material that can help me? Thanks a lot, hope for your reply.

**Comment by sebastianstarke** [comment]
Hello, the IK solver implementation is mainly based on CCD. However instead of solving a single target position, it is extended to handle both position and rotation for multiple end effectors simultaneously. There's lots of material out there that covers how CCD works, which basically operates in Cartesian space rather than joint space to optimize the pose (different benefits and limitations though). The code is pretty straightforward, but let me know if any questions!

**Comment by sebastianstarke** [comment]
Hello, the IK solver implementation is mainly based on CCD. However instead of solving a single target position, it is extended to handle both position and rotation for multiple end effectors simultaneously. There's lots of material out there that covers how CCD works, which basically operates in Cartesian space rather than joint space to optimize the pose (different benefits and limitations though). The code should be pretty straightforward, but let me know if any questions!

**Comment by zll961020** [comment]
@sebastianstarke Thank you very much! I will go to know more about CCD. By the way, when I debug your C# code in IK solver, I found that when the current bone's global rotation is set to a new value, and its child bone's global transform will change at the same time until the end bone of chain while its parent bone's global transform doesn't change so as until to the root bone. This update mechanism seems done automatically by Unity Engine, is that right?

**Comment by pauzii** [comment]
Yes, the mechanism you are describing is known as forward kinematics (FK) and is automatically solved by Unity.
