### ISSUE TITLE
Set custom character 

### ISSUE THREAD

**Issue by TerraUnity** [sebastianstarke/AI4Animation#8]
how to sync user custom character with the system ? does it need a special rig ? is there documents I can find about this ?

**Comment by doctorpangloss** [comment]
You would have to write a function that retargets the existing Bio Adam model to other bipeds.

**Comment by sebastianstarke** [comment]
I would suggest just take the skeleton from the mocap, and skin the character you want to animate with it. That's what I also did for Adam - he's not having his original skeletal structure anymore.

**Comment by sebastianstarke** [comment]
I would suggest just taking the skeleton from the mocap, and then skin the character you want to animate with it. That's what I also did for Adam - he's not having his original skeletal structure anymore if you look at it's hierarchy.

**Comment by sebastianstarke** [comment]
I would suggest to simply take the skeleton from the mocap, and then skin the character you want to animate with it. That's what I also did for Adam - he's not having his original skeletal structure anymore.

**Comment by siamaksalman** [comment]
@doctorpangloss can you please share your retarget solution or any documents about it ?

**Comment by siamaksalman** [comment]
We made a simple model out of boxes in 3ds Max with exact bone structure and count (28 bones) even with exact same names just like the Adam demo scene and finally skinned it properly. The following image shows the setup in Unity.

![photo_2018-06-27_12-05-51 2](https://user-images.githubusercontent.com/5879053/41961236-29753e30-7a07-11e8-908a-db0a03bcb252.jpg)

But when we go to the game, the character meshes get deformed and being messed up as shown in the following image.

![photo_2018-06-27_12-05-51](https://user-images.githubusercontent.com/5879053/41961389-9b44238c-7a07-11e8-9484-47d76e1d85a7.jpg)

![photo_2018-06-27_12-05-50](https://user-images.githubusercontent.com/5879053/41961403-a37c031c-7a07-11e8-82d9-914584fc2f73.jpg)

We have no idea what's happening here!

**Comment by sebastianstarke** [comment]
Did you use the "Skinning" component that is part of AI4Animation? The thing is that the motion is learned based on the default skeleton transformations from the mocap (i.e. in T-Pose). That means that the animation will immediately apply transformations that are usually not relative to (0,0,0) for every bone, but relative to the default posture of the skeleton that was used for learning. That also means the skinning needs to be done with all rotations of the meshes having that default rotation as well. Is that sort of clear? It's quite difficult to explain I guess. To do the skinning, you should place the skeleton inside your character mesh and let the tool assign the skeleton and compute the skinning. However, your character does more look like a "collection" of meshes, if I'm right? Also, you are using non-uniform scaling as far as I can see. This also causes lots of skewing troubles when applying rotations. Let me know.

**Comment by siamaksalman** [comment]
Hey Sebastian, first of all the whole project is awesome and wanted to thank you for sharing this and answering here.

Actually we're still working on it and made some progress...

We could somehow re-create the bone structure the same as the one available in the "Demo_Original" demo scene but not exactly and wanted to ask if you can share the pre-made bone structure in a 3D format so that we can open it up in Max or Maya to get the exact position/orientation of the bone structure and apply it to our custom character model?

Also didn't get what the Skinning script in project does?! We put the provided skeleton inside the character mesh, add the Skinning script on the Skeleton and assign the variable, hit process and what it does is only making the same structure as an instance with bunch of warnings regarding the demo version! Would you please elaborate more on the Skinning script and the proper way to use it and what it does exactly?

Thanks again for your time. Looking forward to the replies.

![0](https://user-images.githubusercontent.com/5879053/43394020-67650f2e-940e-11e8-8d57-6d56bfcd24b9.png)
![1](https://user-images.githubusercontent.com/5879053/43394021-67a957d8-940e-11e8-909e-44c594ed0616.png)
![2](https://user-images.githubusercontent.com/5879053/43394022-67ece7a0-940e-11e8-8ac9-d1e240b1e42c.png)

**Comment by siamaksalman** [comment]
@sebastianstarke

**Comment by sebastianstarke** [comment]
Oh yeah sorry, missed that one. Regarding the skinning script, you will need to create a file with the name as shown in warning message. Then run it again, and it should be able to process the skinning. However, the demo version “original” does only look at position and velocities. I was so far not able to convert the rotations in expmap format to standard quaternions because of that extra coordinate frame transformation between OpenGL/Maya and Unity 3D. However, the rotations are coming out from the network, so if you find any way getting this done, please let me know ;) I just used the weights from the 2017 paper, and just ported this project as a warm-up, but don’t keep it properly maintained. You should rather use the “Adam” demo, and do the foot placement via IK I think.

**Comment by siamaksalman** [comment]
@sebastianstarke Thanks for the reply we're still working on it, do you think you can share character you showed in your [video](https://youtu.be/Ul0Gilv5wvY?t=1m15s) ?

**Comment by Nachbarino** [comment]
Hi @siamaksalman, i´m also trying to use a different model right now and have encountered similar problems. Were you able to solve them?

**Comment by daehwankim112** [comment]
Hello @sebastianstarke ! Thank you so much for your papers and sharing the project on Git. I would love to reproduce your work in 2019 Neural State Machine paper with a custom character to understand the Neural State Machine project and eventually understand Deep Phase as well.

I am following your [advise](https://github.com/sebastianstarke/AI4Animation/issues/8#issuecomment-397894630).

> I would suggest to simply take the skeleton from the mocap, and then skin the character you want to animate with it. That's what I also did for Adam - he's not having his original skeletal structure anymore.

I imported the skeleton into Blender by importing BVH file (Avoid1.bvh), integrated with an armature of my custom character and then assigned vertex groups of my custom character. After assigning, I exported FBX and imported into Unity. The orientation of the upper body bones are very close to the default character made by MotionEditor.cs. However, when I load the motion data by Motion Editor, I am getting a similar rotation and scaling issue with @siamaksalman .

Here are things I have made sure so far:
* Names of the bones in Unity
* Order of the bones in Unity
* Number of the bones in Unity configured by Actor.cs

I am suspecting an issue with weight painting. The lower body bones are also quite tricky because they are pointing downwards in BVH but when it comes to Actor.cs, it seems to assume they are pointing upwards. 

**If you could please share the FBX of Anubis (or if you could guide me where I can buy it), that would be greatly helpful..** It will help me understand what Actor.cs is expecting. Thank you so much!
